import { StyleSheet } from 'react-native';
import { WHEEL_ITEM_HEIGHT } from './constants';

const styles = StyleSheet.create({
  // Sem `zIndex` nem `elevation` aqui. No Android os dois caem no mesmo
  // caminho de elevacao e, num wrapper de tela cheia, quebram a interceptacao
  // de arrasto do ScrollView interno: toque simples passa (por isso os botoes
  // funcionavam), mas o scroll do editor morria. O empilhamento acima da barra
  // inferior vem do `sheetContainer`, que pode ter elevation sem esse efeito.
  container: {
    ...StyleSheet.absoluteFillObject,
  },
  // Durante a saida o estado `visible` do pai ja e falso e elementos elevados
  // (como a faixa do calendario) voltam a montar. A elevacao temporaria mantem
  // a folha acima deles; enquanto aberta o wrapper continua sem elevation para
  // preservar o scroll no Android.
  containerClosing: {
    elevation: 30,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0F1528',
  },
  sheetContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#F6F6FB',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    shadowOpacity: 0,
    elevation: 24,
    overflow: 'hidden',
  },
  keyboardAvoiding: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 20,
    backgroundColor: '#F6F6FB',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 48,
    paddingBottom: 14,
  },
  headerIconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E0EB',
  },
  headerTitleBlock: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  headerTitle: {
    color: '#202236',
    fontSize: 20,
    fontWeight: '800',
  },
  createButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 19,
    backgroundColor: '#3C2BA7',
  },
  createButtonDisabled: {
    backgroundColor: '#C9C5DB',
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingTop: 6,
    paddingBottom: 48,
  },
  identityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E3E1EC',
    padding: 14,
    gap: 14,
  },
  mediaPreview: {
    width: 76,
    height: 76,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  mediaPreviewImage: {
    width: 76,
    height: 76,
    borderRadius: 18,
    resizeMode: 'cover',
  },
  identityContent: {
    flex: 1,
    minWidth: 0,
  },
  titleColumn: {
    alignSelf: 'stretch',
    position: 'relative',
  },
  titleInput: {
    alignSelf: 'stretch',
    fontSize: 20,
    fontWeight: '700',
    color: '#202236',
    textAlign: 'left',
    paddingHorizontal: 0,
    paddingTop: 5,
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E2E0EB',
  },
  counter: {
    alignSelf: 'flex-end',
    color: '#686D80',
    marginTop: 4,
    fontSize: 10,
    fontWeight: '600',
  },
  appearanceSection: {
    marginTop: 20,
    marginBottom: 22,
  },
  appearanceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 3,
    marginBottom: 10,
  },
  selectedColorSample: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  paletteContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E3E1EC',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  colorDotOuter: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  colorDotOuterSelected: {
    borderWidth: 2,
    borderColor: '#3C2BA7',
  },
  colorDot: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(37, 42, 54, 0.18)',
  },
  sectionBlock: {
    marginBottom: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 9,
    paddingHorizontal: 3,
  },
  sectionHeaderText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    color: '#665BC2',
  },
  listContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E3E1EC',
    overflow: 'hidden',
  },
  subtasksPanel: {
    marginTop: 0,
    gap: 10,
  },
  subtasksTitle: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
    color: '#665BC2',
    marginLeft: 3,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  subtasksCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 12,
    borderWidth: 1,
    borderColor: '#E3E1EC',
    overflow: 'hidden',
    zIndex: 1,
  },
  quantumModeRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  quantumModeButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E3E1EC',
  },
  quantumModeButtonSelected: {
    backgroundColor: '#EFECFF',
    borderColor: '#C8C0F1',
  },
  quantumModeButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#303643',
  },
  quantumModeButtonTextSelected: {
    color: '#3C2BA7',
  },
  quantumTimerRow: {
    flexDirection: 'row',
    gap: 12,
  },
  quantumCountRow: {
    flexDirection: 'row',
    gap: 12,
  },
  quantumAnimationSection: {
    gap: 8,
  },
  quantumAnimationRow: {
    flexDirection: 'row',
    gap: 12,
  },
  quantumField: {
    flex: 1,
    gap: 8,
  },
  quantumFieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#626A78',
  },
  quantumFieldInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 11,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#252A36',
    borderWidth: 1,
    borderColor: '#E1E3E8',
    textAlign: 'center',
  },
  row: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E8E9ED',
  },
  rowMain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 66,
    paddingVertical: 10,
  },
  rowLast: {
    borderBottomWidth: 0,
  },
  rowDisabled: {
    opacity: 0.5,
  },
  // A linha passa a quebrar para o erro ocupar a largura inteira embaixo do
  // valor, em vez de disputar espaco horizontal com ele.
  rowHasError: {
    paddingBottom: 10,
  },
  rowErrorText: {
    width: '100%',
    marginTop: 6,
    fontSize: 12,
    lineHeight: 16,
    // 5.39:1 no mais claro dos seis fundos do editor (WCAG AA para texto).
    color: '#B3261E',
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  rowTextColumn: {
    flex: 1,
    minWidth: 0,
  },
  rowLabelWithInfo: {
    flex: 1,
    position: 'relative',
  },
  rowIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 11,
  },
  rowLabel: {
    fontSize: 11,
    color: '#69707D',
    fontWeight: '700',
    marginBottom: 2,
  },
  rowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 3,
    paddingLeft: 3,
    minWidth: 26,
    minHeight: 36,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  rowValue: {
    color: '#252A36',
    fontSize: 14,
    fontWeight: '600',
  },
  overlayContainer: {
    flex: 1,
    backgroundColor: '#F6F6FB',
  },
  overlayCard: {
    flex: 1,
    backgroundColor: '#F6F6FB',
    paddingTop: 4,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  overlayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 52,
    marginBottom: 18,
  },
  overlayBackButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E0EB',
  },
  overlayTitleContainer: {
    flex: 1,
    marginLeft: 12,
    marginRight: 8,
  },
  overlayTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#202236',
    textAlign: 'left',
  },
  overlaySubtitle: {
    fontSize: 12,
    color: '#686D80',
    textAlign: 'left',
    marginTop: 1,
  },
  overlayApplyButton: {
    minWidth: 64,
    minHeight: 38,
    paddingHorizontal: 12,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECE9FF',
  },
  overlayApplyText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#3C2BA7',
  },
  overlayApplyTextDisabled: {
    color: '#9298A5',
  },
  overlayScroll: {
    flex: 1,
  },
  overlayScrollContent: {
    paddingBottom: 32,
  },
  optionList: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E3E1EC',
    overflow: 'hidden',
  },
  typePreviewSection: {
    marginTop: 24,
    gap: 10,
  },
  typePreviewLabel: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.6,
    color: '#7F8A9A',
    textTransform: 'uppercase',
  },
  typePreviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  typePreviewWaterFallbackFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
    overflow: 'hidden',
  },
  typePreviewWaterWave: {
    position: 'absolute',
    left: 0,
    top: 0,
  },
  typePreviewInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  typePreviewEmoji: {
    fontSize: 34,
  },
  typePreviewEmojiImage: {
    width: 46,
    height: 46,
    borderRadius: 23,
    resizeMode: 'cover',
  },
  typePreviewDetails: {
    marginLeft: 12,
    flex: 1,
  },
  typePreviewTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  typePreviewTime: {
    marginTop: 4,
    fontSize: 13,
    color: '#59636f',
  },
  typePreviewSummary: {
    marginTop: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d7dbeb',
  },
  typePreviewSummaryText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#3c2ba7',
  },
  typePreviewToggle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#767c8f',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  tagPanel: {
    gap: 16,
  },
  tagCreator: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E3E1EC',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  tagInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: '#1F2742',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#E1E3E7',
  },
  tagAddButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: '#3C2BA7',
  },
  tagAddButtonDisabled: {
    backgroundColor: '#B8C4D6',
  },
  tagAddButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 15,
  },
  tagAddButtonTextDisabled: {
    opacity: 0.6,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    minHeight: 64,
    paddingVertical: 13,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E8E9EC',
  },
  optionItemSelected: {
    backgroundColor: '#F1EFFF',
  },
  optionItemLast: {
    borderBottomWidth: 0,
  },
  optionLabelColumn: {
    flexShrink: 1,
  },
  optionLabel: {
    color: '#292C40',
    fontSize: 15,
    fontWeight: '500',
  },
  optionLabelSelected: {
    fontWeight: '600',
    color: '#3C2BA7',
  },
  optionHint: {
    marginTop: 2,
    color: '#59636F',
    fontSize: 13,
  },
  radioOuter: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#C7CBD2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterActive: {
    borderColor: '#BFB7EA',
    backgroundColor: '#ECE9FF',
  },
  subtasksList: {
    gap: 0,
  },
  subtaskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 4,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E2E8F5',
  },
  subtaskItemLast: {
    borderBottomWidth: 0,
  },
  subtaskText: {
    flex: 1,
    color: '#1F2742',
    fontSize: 15,
    fontWeight: '600',
  },
  subtaskRemoveButton: {
    padding: 4,
  },
  subtaskComposer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 4,
    paddingVertical: 8,
  },
  subtaskComposerWithDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#E2E8F5',
    paddingTop: 10,
  },
  subtaskComposerInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2742',
    paddingVertical: 0,
  },
  subtaskComposerAdd: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F5',
  },
  subtaskComposerAddDisabled: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EDF1F7',
  },
  subtasksPanelHint: {
    color: '#7F8A9A',
    fontSize: 13,
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  quickSelectRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  datePanel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E3E1EC',
    paddingHorizontal: 12,
    paddingVertical: 14,
  },
  quickSelectButton: {
    minHeight: 38,
    paddingVertical: 8,
    paddingHorizontal: 13,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3E1EC',
  },
  quickSelectButtonActive: {
    backgroundColor: '#ECE9FF',
    borderColor: '#C8C0F1',
  },
  quickSelectButtonDisabled: {
    opacity: 0.35,
  },
  quickSelectLabel: {
    fontSize: 14,
    color: '#1F2742',
    fontWeight: '600',
  },
  quickSelectLabelActive: {
    color: '#3C2BA7',
  },
  quickSelectLabelDisabled: {
    color: '#7F8A9A',
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  calendarNavButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E3E1EC',
  },
  calendarHeaderText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2742',
  },
  weekdayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  weekdayLabel: {
    flex: 1,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '600',
    color: '#7F8A9A',
  },
  // Correção aqui: renomeando e adicionando estilos que faltavam para o calendário
  weekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  dayCell: {
    flex: 1,
    marginHorizontal: 2,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayCellEmpty: {
    flex: 1,
    marginHorizontal: 2,
    height: 40,
  },
  dayCellSelected: {
    backgroundColor: '#3C2BA7',
  },
  dayCellDisabled: {
    opacity: 0.3,
  },
  dayCellRepeating: {
    backgroundColor: '#ECE9FF',
  },
  dayCellText: {
    fontSize: 16,
    color: '#1F2742',
    fontWeight: '600',
  },
  dayCellTextSelected: {
    color: '#FFFFFF',
  },
  dayCellTextDisabled: {
    color: '#1F2742',
  },
  dayCellTextRepeating: {
    color: '#1F2742',
    fontWeight: '600',
  },
  repeatPanel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 15,
    paddingVertical: 14,
    gap: 16,
    borderWidth: 1,
    borderColor: '#E3E1EC',
  },
  repeatContent: {
    gap: 18,
  },
  weekdayGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    gap: 10,
  },
  weekdayPill: {
    flex: 1,
    height: 44,
    borderRadius: 14,
    backgroundColor: '#F7F6FA',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E3E1EC',
  },
  weekdayPillActive: {
    backgroundColor: '#3C2BA7',
    borderColor: '#3C2BA7',
  },
  weekdayPillLabel: {
    color: '#556070',
    fontWeight: '700',
    fontSize: 15,
  },
  weekdayPillLabelActive: {
    color: '#FFFFFF',
  },
  monthDayGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingHorizontal: 12,
    rowGap: 10,
    columnGap: 10,
  },
  monthDayCell: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: '#F7F6FA',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E3E1EC',
  },
  monthDayCellActive: {
    backgroundColor: '#3C2BA7',
    borderColor: '#3C2BA7',
  },
  monthDayLabel: {
    color: '#556070',
    fontWeight: '700',
  },
  monthDayLabelActive: {
    color: '#FFFFFF',
  },
  timeGroupsSection: {
    paddingHorizontal: 4,
  },
  timeGroupsEmptyCard: {
    minHeight: 76,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#D8D3F2',
    backgroundColor: '#F7F5FF',
    paddingHorizontal: 13,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  timeGroupsEmptyIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#E9E4FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeGroupsEmptyCopy: {
    flex: 1,
    gap: 3,
  },
  timeGroupsEmptyTitle: {
    color: '#28204F',
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '700',
  },
  timeGroupsEmptyHint: {
    color: '#726C86',
    fontSize: 12,
    lineHeight: 17,
  },
  timeGroupsConfigured: {
    gap: 0,
  },
  timeGroupsHeadingRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
    gap: 10,
  },
  timeGroupsHeadingCopy: {
    flex: 1,
    gap: 2,
  },
  timeGroupsHeading: {
    color: '#28204F',
    fontSize: 15,
    fontWeight: '700',
  },
  timeGroupsHeadingHint: {
    color: '#7A748B',
    fontSize: 12,
    lineHeight: 16,
  },
  timeGroupsClearButton: {
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  timeGroupsClearLabel: {
    color: '#8F3F55',
    fontSize: 12,
    fontWeight: '700',
  },
  timeGroupCard: {
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#DDD9EC',
    backgroundColor: '#FAF9FD',
    padding: 12,
    gap: 12,
  },
  timeGroupHeader: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  timeGroupNumberBadge: {
    width: 27,
    height: 27,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E9E4FF',
  },
  timeGroupNumber: {
    color: '#3C2BA7',
    fontSize: 13,
    fontWeight: '800',
  },
  timeGroupTitle: {
    flex: 1,
    color: '#28204F',
    fontSize: 14,
    fontWeight: '700',
  },
  timeGroupRemoveButton: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FBEFF2',
  },
  timeGroupDayGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  timeGroupDayPill: {
    minWidth: 38,
    height: 36,
    paddingHorizontal: 11,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#DDD9E9',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeGroupMonthDayPill: {
    minWidth: 36,
    paddingHorizontal: 8,
  },
  timeGroupDayPillActive: {
    borderColor: '#3C2BA7',
    backgroundColor: '#3C2BA7',
  },
  timeGroupDayLabel: {
    color: '#68627A',
    fontSize: 13,
    fontWeight: '700',
  },
  timeGroupDayLabelActive: {
    color: '#FFFFFF',
  },
  timeGroupAddRow: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
  },
  timeGroupAddLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#DDD9EC',
  },
  timeGroupAddButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginHorizontal: 10,
    backgroundColor: '#3C2BA7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timePanel: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 15,
    gap: 18,
    borderWidth: 1,
    borderColor: '#E3E1EC',
  },
  intervalSection: {
    marginTop: 10,
    gap: 12,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  intervalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 2,
  },
  intervalLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2742',
  },
  intervalValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  intervalValue: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4B5563',
  },
  intervalChevron: {
    marginLeft: 4,
  },
  endDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  endDatePickerContainer: {
    marginTop: 6,
  },
  specifiedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  specifiedLabelGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  specifiedIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: '#F0EEFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  specifiedTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2742',
  },
  specifiedSubtitle: {
    fontSize: 13,
    color: '#7F8A9A',
    marginTop: 2,
  },
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: '#E9E7F1',
    borderRadius: 15,
    padding: 4,
    gap: 4,
  },
  segmentedButton: {
    flex: 1,
    borderRadius: 11,
    paddingVertical: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentedButtonActive: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E0EB',
  },
  segmentedButtonLabel: {
    fontSize: 14,
    color: '#54627A',
    fontWeight: '600',
  },
  segmentedButtonLabelActive: {
    color: '#3C2BA7',
  },
  wheelGroup: {
    marginTop: 18,
    marginBottom: 14,
    gap: 10,
  },
  wheelArea: {
    position: 'relative',
    paddingHorizontal: 12,
    height: WHEEL_ITEM_HEIGHT * 5,
    justifyContent: 'center',
  },
  wheelHighlight: {
    position: 'absolute',
    left: 12,
    right: 12,
    top: WHEEL_ITEM_HEIGHT * 2,
    height: WHEEL_ITEM_HEIGHT,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#DDD9EE',
    backgroundColor: '#F2F0FA',
  },
  wheelRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    gap: 12,
  },
  wheelColumn: {
    flex: 1,
    height: '100%',
    maxHeight: WHEEL_ITEM_HEIGHT * 5,
    flexBasis: 0,
  },
  wheelColumnContent: {
    paddingVertical: WHEEL_ITEM_HEIGHT * 2,
  },
  wheelItem: {
    height: WHEEL_ITEM_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wheelItemText: {
    fontSize: 18,
    color: '#636d7c',
    fontWeight: '600',
  },
  wheelItemTextActive: {
    color: '#1F2742',
    fontSize: 24,
    fontWeight: '700',
  },
  wheelLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  wheelLabel: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.6,
    color: '#7F8A9A',
    textTransform: 'uppercase',
  },
  wheelDivider: {
    alignSelf: 'center',
    fontSize: 26,
    fontWeight: '700',
    color: '#1F2742',
    marginHorizontal: 2,
  },
  periodSection: {
    marginTop: 6,
    gap: 12,
  },
  periodLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#7F8A9A',
    textAlign: 'center',
  },
  periodLabelSpacer: {
    marginTop: 2,
  },

  infoLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  infoIconButton: {
    width: 26,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inlineInfoContainer: {
    overflow: 'hidden',
  },
  inlineInfoSurface: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: '#EFEEF5',
  },
  inlineInfoText: {
    color: '#67677A',
    fontSize: 12,
    lineHeight: 17,
  },
});

export default styles;
