import { StyleSheet } from 'react-native';
import { WHEEL_ITEM_HEIGHT } from './constants';

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 300,
    elevation: 30,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0F1528',
  },
  sheetContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#DDE9FF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 24,
    overflow: 'hidden',
  },
  keyboardAvoiding: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 12,
  },
  infoBackdropDismiss: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 4,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 12,
  },
  createButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#1F2742',
  },
  createButtonDevToolsOffset: {
    marginRight: 56,
  },
  createButtonDisabled: {
    backgroundColor: '#B7C2D6',
  },
  createButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 15,
  },
  createButtonTextDisabled: {
    color: '#E5EBF6',
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingBottom: 48,
  },
  identityRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    marginTop: 8,
    marginBottom: 24,
  },
  iconColumn: {
    alignItems: 'center',
    gap: 8,
  },
  iconPreview: {
    width: 72,
    height: 72,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  iconPreviewImage: {
    width: 72,
    height: 72,
    borderRadius: 24,
    resizeMode: 'cover',
  },
  iconPreviewEmoji: {
    fontSize: 38,
    textAlign: 'center',
  },
  iconBadge: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1F2742',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  iconActionLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  iconActionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#61708A',
  },
  titleColumn: {
    flex: 1,
    justifyContent: 'center',
    minHeight: 72,
  },
  titleInput: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1F2742',
    textAlign: 'left',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(31, 39, 66, 0.12)',
  },
  counter: {
    textAlign: 'right',
    color: '#7F8A9A',
    marginTop: 6,
    fontSize: 12,
    fontWeight: '500',
  },
  paletteContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 28,
  },
  colorDot: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(18, 32, 53, 0.2)',
  },
  colorDotSelected: {
    borderWidth: 2,
    borderColor: '#1F2742',
  },
  listContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    overflow: 'visible',
  },
  listContainerInfoActive: {
    zIndex: 80,
    elevation: 80,
  },
  subtasksPanel: {
    marginTop: 4,
    gap: 12,
  },
  subtasksTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2742',
    marginLeft: 6,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    position: 'relative',
    zIndex: 20,
    elevation: 20,
  },
  subtasksCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    overflow: 'hidden',
    zIndex: 1,
  },
  quantumModeRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  quantumModeButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: '#EEF3FF',
    alignItems: 'center',
  },
  quantumModeButtonSelected: {
    backgroundColor: '#1F2742',
  },
  quantumModeButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2742',
  },
  quantumModeButtonTextSelected: {
    color: '#FFFFFF',
  },
  quantumTimerRow: {
    flexDirection: 'row',
    gap: 12,
  },
  quantumCountRow: {
    flexDirection: 'row',
    gap: 12,
  },
  quantumAnimationSection: {
    gap: 8,
  },
  quantumAnimationRow: {
    flexDirection: 'row',
    gap: 12,
  },
  quantumField: {
    flex: 1,
    gap: 8,
  },
  quantumFieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#7F8A9A',
  },
  quantumFieldInput: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#1F2742',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(109, 125, 150, 0.16)',
    textAlign: 'center',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(109, 125, 150, 0.16)',
  },
  rowLast: {
    borderBottomWidth: 0,
  },
  rowDisabled: {
    opacity: 0.5,
  },
  // A linha passa a quebrar para o erro ocupar a largura inteira embaixo do
  // valor, em vez de disputar espaco horizontal com ele.
  rowHasError: {
    flexWrap: 'wrap',
    paddingBottom: 10,
  },
  rowErrorText: {
    width: '100%',
    marginTop: 6,
    fontSize: 12,
    lineHeight: 16,
    // 5.39:1 no mais claro dos seis fundos do editor (WCAG AA para texto).
    color: '#B3261E',
  },
  rowInfoVisible: {
    zIndex: 120,
    elevation: 120,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  rowLabelWithInfo: {
    flex: 1,
    position: 'relative',
    overflow: 'visible',
  },
  rowLabelWithInfoVisible: {
    zIndex: 130,
    elevation: 130,
  },
  rowIconContainer: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF3FF',
    marginRight: 12,
  },
  rowLabel: {
    flexShrink: 1,
    fontSize: 16,
    color: '#1F2742',
    fontWeight: '600',
  },
  rowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginLeft: 12,
  },
  rowValue: {
    color: '#7F8A9A',
    fontSize: 15,
  },
  overlayContainer: {
    flex: 1,
    backgroundColor: '#DDE9FF',
  },
  overlayCard: {
    flex: 1,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    paddingTop: 12,
    paddingHorizontal: 20,
    paddingBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 10,
    overflow: 'visible',
  },
  overlayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  overlayTitleContainer: {
    flex: 1,
    marginHorizontal: 12,
  },
  overlayTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1F2742',
    textAlign: 'center',
  },
  overlaySubtitle: {
    fontSize: 14,
    color: '#7F8A9A',
    textAlign: 'center',
    marginTop: 2,
  },
  overlayApplyButton: {
    minWidth: 54,
    alignItems: 'flex-end',
  },
  overlayApplyText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2742',
  },
  overlayApplyTextDisabled: {
    color: '#B0BDCF',
  },
  overlayScroll: {
    flex: 1,
  },
  overlayScrollContent: {
    paddingBottom: 32,
  },
  optionList: {
    backgroundColor: '#F5F7FF',
    borderRadius: 20,
    overflow: 'hidden',
  },
  typePreviewSection: {
    marginTop: 24,
    gap: 10,
  },
  typePreviewLabel: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.6,
    color: '#7F8A9A',
    textTransform: 'uppercase',
  },
  typePreviewCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    backgroundColor: '#FFFFFF',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  typePreviewWaterFallbackFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 18,
    overflow: 'hidden',
  },
  typePreviewWaterWave: {
    position: 'absolute',
    left: 0,
    top: 0,
  },
  typePreviewInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  typePreviewEmoji: {
    fontSize: 34,
  },
  typePreviewEmojiImage: {
    width: 46,
    height: 46,
    borderRadius: 23,
    resizeMode: 'cover',
  },
  typePreviewDetails: {
    marginLeft: 12,
    flex: 1,
  },
  typePreviewTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  typePreviewTime: {
    marginTop: 4,
    fontSize: 13,
    color: '#59636f',
  },
  typePreviewSummary: {
    marginTop: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d7dbeb',
  },
  typePreviewSummaryText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#3c2ba7',
  },
  typePreviewToggle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#767c8f',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  tagPanel: {
    gap: 18,
  },
  tagCreator: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#EEF3FF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  tagInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: '#1F2742',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(109, 125, 150, 0.16)',
  },
  tagAddButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: '#1F2742',
  },
  tagAddButtonDisabled: {
    backgroundColor: '#B8C4D6',
  },
  tagAddButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 15,
  },
  tagAddButtonTextDisabled: {
    opacity: 0.6,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(109, 125, 150, 0.12)',
  },
  optionItemSelected: {
    backgroundColor: '#E4ECFF',
  },
  optionItemLast: {
    borderBottomWidth: 0,
  },
  optionLabelColumn: {
    flexShrink: 1,
  },
  optionLabel: {
    color: '#1F2742',
    fontSize: 16,
    fontWeight: '500',
  },
  optionLabelSelected: {
    fontWeight: '600',
  },
  optionHint: {
    marginTop: 2,
    color: '#59636F',
    fontSize: 13,
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#B8C4D6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterActive: {
    borderColor: '#1F2742',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#1F2742',
  },
  subtasksList: {
    gap: 0,
  },
  subtaskItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 4,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E2E8F5',
  },
  subtaskItemLast: {
    borderBottomWidth: 0,
  },
  subtaskText: {
    flex: 1,
    color: '#1F2742',
    fontSize: 15,
    fontWeight: '600',
  },
  subtaskRemoveButton: {
    padding: 4,
  },
  subtaskComposer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 4,
    paddingVertical: 8,
  },
  subtaskComposerWithDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#E2E8F5',
    paddingTop: 10,
  },
  subtaskComposerInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2742',
    paddingVertical: 0,
  },
  subtaskComposerAdd: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F5',
  },
  subtaskComposerAddDisabled: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EDF1F7',
  },
  subtasksPanelHint: {
    color: '#7F8A9A',
    fontSize: 13,
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  quickSelectRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  quickSelectButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: '#EEF3FF',
  },
  quickSelectButtonActive: {
    backgroundColor: '#1F2742',
  },
  quickSelectButtonDisabled: {
    opacity: 0.35,
  },
  quickSelectLabel: {
    fontSize: 14,
    color: '#1F2742',
    fontWeight: '600',
  },
  quickSelectLabelActive: {
    color: '#FFFFFF',
  },
  quickSelectLabelDisabled: {
    color: '#7F8A9A',
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  calendarHeaderText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2742',
  },
  weekdayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  weekdayLabel: {
    flex: 1,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '600',
    color: '#7F8A9A',
  },
  // Correção aqui: renomeando e adicionando estilos que faltavam para o calendário
  weekRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  dayCell: {
    flex: 1,
    marginHorizontal: 4,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayCellEmpty: {
    flex: 1,
    marginHorizontal: 4,
    height: 44,
  },
  dayCellSelected: {
    backgroundColor: '#1F2742',
  },
  dayCellDisabled: {
    opacity: 0.3,
  },
  dayCellRepeating: {
    backgroundColor: 'rgba(31, 39, 66, 0.18)',
  },
  dayCellText: {
    fontSize: 16,
    color: '#1F2742',
    fontWeight: '600',
  },
  dayCellTextSelected: {
    color: '#FFFFFF',
  },
  dayCellTextDisabled: {
    color: '#1F2742',
  },
  dayCellTextRepeating: {
    color: '#1F2742',
    fontWeight: '600',
  },
  repeatPanel: {
    backgroundColor: '#F5F7FF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  repeatContent: {
    gap: 18,
  },
  weekdayGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    gap: 10,
  },
  weekdayPill: {
    flex: 1,
    height: 44,
    borderRadius: 20,
    backgroundColor: '#F2F6FF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#A3B7D7',
  },
  weekdayPillActive: {
    backgroundColor: '#E3EBFF',
    borderColor: '#1F2742',
  },
  weekdayPillLabel: {
    color: '#556070',
    fontWeight: '700',
    fontSize: 15,
  },
  weekdayPillLabelActive: {
    color: '#1F2742',
  },
  monthDayGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingHorizontal: 12,
    rowGap: 10,
    columnGap: 10,
  },
  monthDayCell: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F2F6FF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#A3B7D7',
  },
  monthDayCellActive: {
    backgroundColor: '#E3EBFF',
    borderColor: '#1F2742',
  },
  monthDayLabel: {
    color: '#556070',
    fontWeight: '700',
  },
  monthDayLabelActive: {
    color: '#1F2742',
  },
  timePanel: {
    backgroundColor: '#F5F7FF',
    borderRadius: 20,
    padding: 16,
    gap: 18,
  },
  intervalSection: {
    marginTop: 10,
    gap: 12,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  intervalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 2,
  },
  intervalLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2742',
  },
  intervalValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  intervalValue: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4B5563',
  },
  intervalChevron: {
    marginLeft: 4,
  },
  endDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  endDatePickerContainer: {
    marginTop: 6,
  },
  specifiedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  specifiedLabelGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  specifiedIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E3EBFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  specifiedTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2742',
  },
  specifiedSubtitle: {
    fontSize: 13,
    color: '#7F8A9A',
    marginTop: 2,
  },
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: '#E3EBFF',
    borderRadius: 18,
    padding: 4,
    gap: 4,
  },
  segmentedButton: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentedButtonActive: {
    backgroundColor: '#FFFFFF',
    elevation: 2,
  },
  segmentedButtonLabel: {
    fontSize: 14,
    color: '#54627A',
    fontWeight: '600',
  },
  segmentedButtonLabelActive: {
    color: '#1F2742',
  },
  wheelGroup: {
    marginTop: 18,
    marginBottom: 14,
    gap: 10,
  },
  wheelArea: {
    position: 'relative',
    paddingHorizontal: 12,
    height: WHEEL_ITEM_HEIGHT * 5,
    justifyContent: 'center',
  },
  wheelHighlight: {
    position: 'absolute',
    left: 12,
    right: 12,
    top: WHEEL_ITEM_HEIGHT * 2,
    height: WHEEL_ITEM_HEIGHT,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(31,39,66,0.16)',
    backgroundColor: '#FFFFFF',
    shadowColor: '#1F2742',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 8,
  },
  wheelRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    gap: 12,
  },
  wheelColumn: {
    flex: 1,
    height: '100%',
    maxHeight: WHEEL_ITEM_HEIGHT * 5,
    flexBasis: 0,
  },
  wheelColumnContent: {
    paddingVertical: WHEEL_ITEM_HEIGHT * 2,
  },
  wheelItem: {
    height: WHEEL_ITEM_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wheelItemText: {
    fontSize: 18,
    color: '#636d7c',
    fontWeight: '600',
  },
  wheelItemTextActive: {
    color: '#1F2742',
    fontSize: 24,
    fontWeight: '700',
  },
  wheelLabelsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  wheelLabel: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.6,
    color: '#7F8A9A',
    textTransform: 'uppercase',
  },
  wheelDivider: {
    alignSelf: 'center',
    fontSize: 26,
    fontWeight: '700',
    color: '#1F2742',
    marginHorizontal: 2,
  },
  periodSection: {
    marginTop: 6,
    gap: 12,
  },
  periodLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#7F8A9A',
    textAlign: 'center',
  },
  periodLabelSpacer: {
    marginTop: 2,
  },

  infoLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  infoIconButton: {
    padding: 2,
  },
  floatingInfoBubble: {
    position: 'absolute',
    top: 28,
    left: 0,
    backgroundColor: '#eef3ff',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#d5dff5',
    zIndex: 300,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 40,
  },
  rowFloatingInfoBubble: {
    left: 46,
    right: 0,
  },
  previewFloatingInfoBubble: {
    left: 0,
    right: 0,
  },
  sectionFloatingInfoBubble: {
    left: 6,
    right: -220,
  },
  inlineInfoText: {
    color: '#425071',
    fontSize: 12,
    lineHeight: 16,
  },
});

export default styles;
