import { StyleSheet } from 'react-native';
import {
  CALENDAR_DAY_SIZE,
  WEEKDAY_ROW_HEIGHT,
  WHEEL_ITEM_HEIGHT,
  WHEEL_VISIBLE_ITEMS,
} from '../constants/layout';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f6f6fb',
    position: 'relative',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#f6f6fb',
  },
  appFrame: {
    flex: 1,
    backgroundColor: '#f6f6fb',
  },
  confettiContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 20,
    elevation: 10,
  },
  confettiPiece: {
    position: 'absolute',
    borderRadius: 2,
    opacity: 0.9,
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 48,
    gap: 16,
  },
  heading: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1a1a2e',
  },
  description: {
    fontSize: 16,
    lineHeight: 22,
    color: '#4b4b63',
  },
  todayContent: {
    flexGrow: 1,
    paddingBottom: 48,
  },
  todayHeader: {
    marginBottom: 20,
  },
  todayTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1a1a2e',
  },
  todaySubtitle: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: '600',
  },
  todaySubtitleSuccess: {
    color: '#2f9e44',
  },
  todaySubtitleInProgress: {
    color: '#6f7a86',
  },
  todayDateEyebrow: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 1.2,
    color: '#8a8fa3',
    marginBottom: 4,
  },
  todayProgressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  todayProgressPct: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: '700',
  },
  todayProgressPctInProgress: {
    color: '#3c2ba7',
  },
  todayProgressTrack: {
    marginTop: 12,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#e9e7f4',
    overflow: 'hidden',
  },
  todayProgressFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: '#3c2ba7',
  },
  todayProgressFillComplete: {
    backgroundColor: '#2f9e44',
  },
  daySelector: {
    width: '100%',
    alignSelf: 'stretch',
    marginBottom: 12,
    overflow: 'hidden',
  },
  daySelectorList: {
    width: '100%',
    flexGrow: 0,
  },
  todayTemporalActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
    marginBottom: 20,
  },
  todayTemporalButton: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#d9d5ee',
    backgroundColor: '#f7f5ff',
  },
  todayTemporalButtonPrimary: {
    borderColor: '#3c2ba7',
    backgroundColor: '#3c2ba7',
  },
  todayTemporalButtonPrimaryText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  tagFilterContainer: {
    marginBottom: 16,
  },
  tagFilterScroll: {
    paddingHorizontal: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tagPill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#edefff',
  },
  tagPillSelected: {
    backgroundColor: '#3c2ba7',
  },
  tagPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3c2ba7',
  },
  tagPillTextSelected: {
    color: '#ffffff',
  },
  dayItem: {
    alignItems: 'center',
  },
  dayLabel: {
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.6,
    color: '#9ba0b0',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  dayLabelSelected: {
    color: '#3c2ba7',
    fontWeight: '800',
  },
  dayNumber: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ecebf5',
    position: 'relative',
  },
  dayNumberSelected: {
    backgroundColor: '#3c2ba7',
    borderColor: '#3c2ba7',
  },
  dayNumberCompleted: {
    backgroundColor: '#d9f2e5',
    borderColor: '#d9f2e5',
  },
  dayNumberText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  dayNumberTextSelected: {
    color: '#ffffff',
  },
  dayNumberTextCompleted: {
    color: '#1f9d6d',
  },
  todayIndicator: {
    position: 'absolute',
    bottom: 6,
    width: '54%',
    height: 3,
    borderRadius: 2,
    backgroundColor: '#3c2ba7',
  },
  todayIndicatorOnSelected: {
    backgroundColor: '#ffffff',
  },
  tasksSection: {
    marginTop: 8,
  },
  todayFirstTask: {
    marginTop: 8,
  },
  todayTaskCell: {
    overflow: 'visible',
  },
  emptyState: {
    fontSize: 15,
    color: '#6f7a86',
    textAlign: 'center',
    paddingHorizontal: 12,
  },
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 20,
  },
  emptyStateIllustration: {
    marginBottom: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e7e9f8',
    borderWidth: 1,
    borderColor: '#d7dbeb',
  },
  taskCard: {
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  waterFillContainer: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 18,
    overflow: 'hidden',
  },
  waterLevelLayer: {
    position: 'absolute',
    left: 0,
    bottom: 0,
  },
  waterWaveLayer: {
    position: 'absolute',
    left: 0,
    top: 0,
  },
  taskCardMain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  quantumStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(26, 26, 46, 0.15)',
  },
  quantumStepperAnimated: {
    overflow: 'hidden',
  },
  quantumStepperButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(26, 26, 46, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantumStepperButtonAdd: {
    backgroundColor: '#3c2ba7',
    borderColor: '#3c2ba7',
  },
  quantumStepperPresets: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  quantumStepperPreset: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
  },
  quantumStepperPresetSelected: {
    backgroundColor: '#3c2ba7',
  },
  quantumStepperPresetText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4a4466',
  },
  quantumStepperPresetTextSelected: {
    color: '#ffffff',
  },
  swipeableWrapper: {
    marginBottom: 14,
    position: 'relative',
    borderRadius: 18,
    backgroundColor: 'transparent',
  },
  swipeableActions: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 168,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f6f6fb',
    borderRadius: 18,
    zIndex: -1,
  },
  swipeActionButton: {
    flex: 1,
    marginHorizontal: 4,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    backgroundColor: '#eef1ff',
  },
  swipeActionCopy: {
    backgroundColor: '#eef1ff',
  },
  swipeActionArchive: {
    backgroundColor: '#3c2ba7',
  },
  swipeActionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1a1a2e',
    textTransform: 'uppercase',
    marginTop: 4,
  },
  swipeActionTextArchive: {
    color: '#ffffff',
  },
  swipeActionButtonDisabled: {
    opacity: 0.55,
  },
  swipeActionTextDisabled: {
    color: '#ffffff',
  },
  taskInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  taskCardContent: {
    flex: 1,
    paddingRight: 12,
  },
  taskEmoji: {
    fontSize: 34,
  },
  taskEmojiImage: {
    width: 46,
    height: 46,
    borderRadius: 23,
    resizeMode: 'cover',
  },
  taskDetails: {
    marginLeft: 12,
    flex: 1,
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  taskTitleCompleted: {
    color: '#6f7a86',
    textDecorationLine: 'line-through',
  },
  taskTime: {
    marginTop: 4,
    fontSize: 13,
    color: '#6f7a86',
  },
  taskSubtaskSummary: {
    marginTop: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d7dbeb',
  },
  taskSubtaskSummaryText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#3c2ba7',
  },
  taskToggle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#c5cadb',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  taskToggleGroup: {
    minWidth: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskToggleStepLabel: {
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '700',
    color: '#777d90',
  },
  taskToggleStepButton: {
    marginTop: 3,
    minHeight: 18,
    paddingHorizontal: 4,
    borderRadius: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
  },
  taskToggleCompleted: {
    backgroundColor: '#3dd598',
    borderColor: '#3dd598',
  },
  taskCardMissed: {
    opacity: 0.55,
  },
  missedBadge: {
    backgroundColor: '#f3f4f8',
    borderWidth: 1,
    borderColor: '#d6dae6',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  missedBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6f7a86',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  detailOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 11, 30, 0.45)',
    justifyContent: 'flex-end',
  },
  detailBackdrop: {
    flex: 1,
  },
  detailCardContainer: {
    padding: 20,
  },
  detailCard: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 20,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  detailHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  detailHeaderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  detailEmoji: {
    fontSize: 36,
  },
  detailEmojiImage: {
    width: 53,
    height: 53,
    borderRadius: 26.5,
    resizeMode: 'cover',
  },
  detailTitleContainer: {
    marginLeft: 12,
    flex: 1,
  },
  detailTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1a1a2e',
  },
  detailTitleLock: {
    opacity: 0.7,
    lineHeight: 20,
  },
  detailTime: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '500',
    color: '#4b4b63',
  },
  detailStreakRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  detailStreakText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#f2732e',
  },
  detailSubtaskSummaryLabel: {
    marginTop: 6,
    fontSize: 12,
    color: '#3c2ba7',
    fontWeight: '600',
  },
  detailToggle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#c5cadb',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  detailToggleCompleted: {
    backgroundColor: '#3dd598',
    borderColor: '#3dd598',
  },
  detailSubtasksContainer: {
    maxHeight: 260,
    marginHorizontal: -4,
    paddingHorizontal: 4,
    marginBottom: 16,
  },
  detailEmptySubtasks: {
    fontSize: 14,
    color: '#6f7a86',
  },
  timerWheelArea: {
    position: 'relative',
    height: WHEEL_ITEM_HEIGHT * WHEEL_VISIBLE_ITEMS,
    justifyContent: 'center',
    paddingHorizontal: 6,
    overflow: 'hidden',
  },
  timerWheelHighlight: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: WHEEL_ITEM_HEIGHT - 4,
    height: WHEEL_ITEM_HEIGHT + 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(31,39,66,0.16)',
    backgroundColor: '#FFFFFF',
    shadowColor: '#1F2742',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 6,
  },
  timerWheelRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    gap: 6,
  },
  timerWheelDivider: {
    alignSelf: 'center',
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2742',
  },
  timerWheelColumn: {
    width: '100%',
  },
  timerWheelColumnWrapper: {
    width: 90,
    height: WHEEL_ITEM_HEIGHT * WHEEL_VISIBLE_ITEMS,
    overflow: 'hidden',
  },
  timerWheelColumnContent: {
    paddingVertical: WHEEL_ITEM_HEIGHT,
  },
  timerWheelItem: {
    height: WHEEL_ITEM_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerWheelItemText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#A3AEC1',
  },
  timerWheelItemTextActive: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1F2742',
  },
  detailSubtaskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: '#d9dcea',
  },
  detailSubtaskIndicator: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: '#c5cadb',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    backgroundColor: '#ffffff',
  },
  detailSubtaskIndicatorCompleted: {
    backgroundColor: '#3dd598',
    borderColor: '#3dd598',
  },
  detailSubtaskText: {
    flex: 1,
    fontSize: 15,
    color: '#1a1a2e',
  },
  detailSubtaskTextCompleted: {
    color: '#6f7a86',
    textDecorationLine: 'line-through',
  },
  detailEditLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingVertical: 12,
    alignSelf: 'center',
  },
  detailEditContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailEditButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#3c2ba7',
  },
  calendarListContent: {
    paddingBottom: 60,
  },
  calendarViewSwitcherWrapper: {
    backgroundColor: '#f6f6fb',
    paddingVertical: 10,
    alignItems: 'center',
  },
  calendarViewSwitcher: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    padding: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  calendarViewSwitcherSegment: {
    flexDirection: 'row',
    gap: 6,
    paddingVertical: 7,
    paddingHorizontal: 18,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarViewSwitcherSegmentActive: {
    backgroundColor: '#3c2ba7',
  },
  calendarViewSwitcherText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6f7a86',
  },
  calendarViewSwitcherTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  calendarWeekdayRow: {
    flexDirection: 'row',
    height: WEEKDAY_ROW_HEIGHT,
    alignItems: 'center',
  },
  calendarWeekdayText: {
    width: CALENDAR_DAY_SIZE,
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '700',
    color: '#6f7a86',
  },
  calendarMonthYear: {
    color: 'rgba(255, 255, 255, 0.85)',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 2.5,
    textShadowColor: 'rgba(0, 0, 0, 0.7)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  calendarWeekdayTextWeekend: {
    color: '#b3a9e0',
  },
  calendarMonthContainer: {
    marginBottom: 32,
    marginHorizontal: 0,
  },
  calendarMonthHeader: {
    height: 100,
    justifyContent: 'flex-end',
    padding: 20,
    marginBottom: 10,
    marginHorizontal: 0,
    borderRadius: 0,
    overflow: 'hidden',
  },
  calendarMonthTitle: {
    color: '#fff',
    fontSize: 26,
    fontWeight: '800',
    textTransform: 'capitalize',
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 8,
  },
  calendarDaysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '100%',
  },
  calendarDayCellWrapper: {
    width: CALENDAR_DAY_SIZE,
    height: CALENDAR_DAY_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarDayText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  // Dia completo: verde-menta suave com check escuro (par #d9f2e5/#1f9d6d da paleta)
  calendarSuccessCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#d9f2e5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Hoje + completo: anel roxo (marca) em volta do check verde (conquista).
  calendarTodayRing: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#3c2ba7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarDayTextPast: {
    color: '#9aa1ad',
  },
  // Adicione estes estilos para o dia atual:
  calendarTodayCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#3c2ba7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarTodayText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  calendarMoodBadge: {
    position: 'absolute',
    top: 0,
    right: 2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 2,
    overflow: 'visible',
  },
  calendarMoodBadgeText: {
    fontSize: 10,
  },
  calendarMoodBadgeImage: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  // Feed de reflexões: posts estilo rede social (espelha reportMoodCard).
  feedPostCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 16,
    marginHorizontal: 20,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 4,
  },
  feedPostHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  feedPostAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#f6f6fb',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  feedPostEmoji: {
    fontSize: 26,
  },
  feedPostAvatarImage: {
    width: '100%',
    height: '100%',
  },
  feedPostTextWrapper: {
    flex: 1,
  },
  feedPostTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1a1a2e',
  },
  feedPostDate: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6f7a86',
    marginTop: 1,
    textTransform: 'capitalize',
  },
  feedMonthHeader: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: '#6f7a86',
    marginHorizontal: 24,
    marginTop: 8,
    marginBottom: 10,
  },
  feedTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 12,
  },
  feedTagChip: {
    backgroundColor: '#f1eefb',
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  feedTagChipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#3c2ba7',
  },
  feedPostNote: {
    fontSize: 14,
    color: '#1a1a2e',
    lineHeight: 20,
    marginTop: 10,
  },
  feedPostPhoto: {
    width: '100%',
    height: 200,
    borderRadius: 14,
    marginTop: 12,
  },
  feedEmptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
    paddingBottom: 40,
  },
  feedEmptyTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1a1a2e',
    marginTop: 14,
    textAlign: 'center',
  },
  feedEmptyText: {
    fontSize: 14,
    color: '#6f7a86',
    lineHeight: 20,
    marginTop: 6,
    textAlign: 'center',
  },
  feedEmptyButton: {
    marginTop: 18,
    backgroundColor: '#3c2ba7',
    borderRadius: 999,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  feedEmptyButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
  },
  bottomBarContainer: {
    width: '100%',
    alignItems: 'stretch',
    backgroundColor: '#ffffff',
  },
  bottomBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    paddingVertical: 12,
    paddingHorizontal: 16,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 8,
    borderTopWidth: 0,
  },
  bottomBarDimmed: {
    opacity: 0.4,
  },
  tabGroup: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 2,
  },
  tabLabel: {
    letterSpacing: 0.2,
    fontWeight: '600',
  },
  activeColor: {
    color: '#3c2ba7',
  },
  inactiveColor: {
    color: '#6f7a86',
  },
  addButton: {
    position: 'absolute',
    top: -32,
    alignSelf: 'center',
    backgroundColor: '#3c2ba7',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#3c2ba7',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 12,
    zIndex: 12,
    overflow: 'visible',
  },
  addButtonActive: {
    backgroundColor: '#ffffff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 10,
  },
  placeholderContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingVertical: 40,
    gap: 8,
  },
  placeholderIconWrapper: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#f0efff',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  placeholderDescription: {
    textAlign: 'center',
    marginTop: 2,
  },
  addButtonBase: {
    position: 'absolute',
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 10,
    zIndex: -1,
  },
  addButtonHalo: {
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    zIndex: -2,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    zIndex: 10,
    overflow: 'hidden',
  },
  fabActionsContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 11,
  },
  fabActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  fabCard: {
    overflow: 'visible',
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 14,
  },
  fabCardBackground: {
    flex: 1,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  fabCardContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fabCardTitle: {
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: 0.1,
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  fabCardSubtitle: {
    color: 'rgba(255, 255, 255, 0.95)',
    textAlign: 'center',
    paddingHorizontal: 4,
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  fabCardIcon: {
    alignSelf: 'center',
  },
  stickyHeader: {
    width: '100%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    overflow: 'hidden',
  },
  stickyHeaderText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
  },
  // --- ESTILOS DO RELATÓRIO ---
  reportOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  reportBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  reportSheet: {
    backgroundColor: '#F6F6FB',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
    width: '100%',
  },
  reportHeaderImage: {
    height: 180,
    backgroundColor: '#1a1a1a',
    padding: 24,
    justifyContent: 'flex-end',
    position: 'relative',
  },
  reportCloseButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 10,
  },
  reportDateContainer: {
    marginBottom: 10,
  },
  reportDateBig: {
    fontSize: 32,
    fontWeight: '800',
    color: '#fff',
  },
  reportYear: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.7)',
    fontWeight: '600',
  },
  reportScrollContent: {
    padding: 24,
    paddingBottom: 50,
  },
  reportSummaryText: {
    fontSize: 16,
    color: '#4b4b63',
    lineHeight: 24,
    marginBottom: 24,
  },
  reportSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a2e',
    marginBottom: 12,
  },
  reportMoodCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 16,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 4,
  },
  reportMoodHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  reportMoodAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#f6f6fb',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  reportMoodEmoji: {
    fontSize: 26,
  },
  reportMoodImage: {
    width: '100%',
    height: '100%',
  },
  reportMoodTextWrapper: {
    flex: 1,
  },
  reportMoodTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1a1a2e',
  },
  reportMoodTags: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6f7a86',
    marginTop: 1,
  },
  reportMoodNote: {
    fontSize: 14,
    color: '#1a1a2e',
    lineHeight: 20,
    marginTop: 12,
  },
  reportMoodPhoto: {
    width: '100%',
    height: 200,
    borderRadius: 14,
    marginTop: 12,
  },
  reportPhotoViewerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportPhotoViewerImage: {
    width: '100%',
    height: '85%',
  },
  reportAddMoodButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(60, 43, 167, 0.25)',
    borderStyle: 'dashed',
    paddingVertical: 14,
    marginBottom: 24,
  },
  reportAddMoodText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#3c2ba7',
  },
  statsCard: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 4,
  },
  gaugeContainer: {
    alignItems: 'center',
    marginBottom: 12,
    justifyContent: 'center',
    minHeight: 144,
  },
  gaugeValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  gaugePercentage: {
    fontSize: 40,
    fontWeight: '800',
    letterSpacing: -1,
    color: '#1a1a2e',
    textAlign: 'center',
  },
  gaugePercentSign: {
    fontSize: 17,
    fontWeight: '800',
    color: '#6f7a86',
    marginBottom: 6,
    marginLeft: 1,
  },
  gaugeLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#9aa1ad',
    marginTop: 2,
    textAlign: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  statBox: {
    flex: 1,
    backgroundColor: '#F8F9FE',
    borderRadius: 16,
    padding: 16,
  },
  statLabel: {
    fontSize: 13,
    color: '#6f7a86',
    fontWeight: '600',
    marginBottom: 8,
  },
  statValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statIconChip: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1a1a2e',
  },
  reportTaskList: {
    gap: 12,
  },
  reportTaskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 16,
    gap: 12,
  },
  reportTaskIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportTaskIconImage: {
    width: 38,
    height: 38,
    borderRadius: 14,
    resizeMode: 'cover',
  },
  reportTaskTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a2e',
  },

  // --- ESTILOS DA REFLEXÃO DO DIA ---
  reflectionSheet: {
    backgroundColor: '#F6F6FB',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    width: '100%',
    paddingTop: 22,
  },
  reflectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    marginBottom: 14,
  },
  reflectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1a1a2e',
  },
  reflectionDate: {
    fontSize: 13,
    fontWeight: '600',
    color: '#8a86a8',
    marginTop: 2,
    textTransform: 'capitalize',
  },
  reflectionScrollContent: {
    paddingHorizontal: 24,
    // Respiro extra pro botão salvar não colar na barra de gestos do celular.
    paddingBottom: 52,
  },
  reflectionQuestion: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1a1a2e',
    marginBottom: 12,
  },
  reflectionMoodRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  reflectionMoodOption: {
    alignItems: 'center',
    width: '18%',
  },
  reflectionMoodCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
    overflow: 'hidden',
  },
  reflectionMoodCircleSelected: {
    borderColor: '#3c2ba7',
    backgroundColor: '#efeaff',
    transform: [{ scale: 1.08 }],
  },
  reflectionMoodImage: {
    width: '100%',
    height: '100%',
    borderRadius: 25,
  },
  reflectionMoodEmoji: {
    fontSize: 28,
  },
  reflectionMoodEmojiDim: {
    opacity: 0.45,
  },
  reflectionMoodLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#6f7a86',
    marginTop: 6,
  },
  reflectionMoodLabelSelected: {
    color: '#3c2ba7',
    fontWeight: '800',
  },
  reflectionHint: {
    fontSize: 11,
    color: '#9a96b8',
    marginBottom: 8,
  },
  reflectionCustomizeButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 18,
    backgroundColor: '#efeaff',
  },
  reflectionCustomizeButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#3c2ba7',
  },
  reflectionTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 18,
  },
  reflectionTagChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: 'rgba(26, 26, 46, 0.08)',
  },
  reflectionTagChipSelected: {
    backgroundColor: '#efeaff',
    borderColor: '#3c2ba7',
  },
  reflectionTagText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6f7a86',
  },
  reflectionTagTextSelected: {
    color: '#3c2ba7',
    fontWeight: '700',
  },
  reflectionPhotoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 18,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#c9c2ec',
    backgroundColor: '#f4f1ff',
    marginBottom: 18,
  },
  reflectionPhotoButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#3c2ba7',
  },
  reflectionPhotoWrapper: {
    alignSelf: 'flex-start',
    marginBottom: 18,
  },
  reflectionPhoto: {
    width: 96,
    height: 96,
    borderRadius: 16,
  },
  reflectionPhotoRemove: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#1a1a2e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reflectionNoteInput: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 16,
    minHeight: 96,
    fontSize: 15,
    color: '#1a1a2e',
    borderWidth: 1,
    borderColor: 'rgba(26, 26, 46, 0.08)',
    marginBottom: 18,
  },
  reflectionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  reflectionRemoveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 26,
    backgroundColor: 'rgba(214, 69, 80, 0.1)',
  },
  reflectionRemoveText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#d64550',
  },
  reflectionSaveButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 14,
    borderRadius: 26,
    backgroundColor: '#3c2ba7',
    shadowColor: '#3c2ba7',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  reflectionSaveButtonDisabled: {
    backgroundColor: '#b9b3d6',
    elevation: 0,
    shadowOpacity: 0,
  },
  reflectionSaveText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ffffff',
  },

  // --- ESTILOS DO GRÁFICO DE DESEMPENHO ---
  perfCard: {
    alignSelf: 'stretch',
    backgroundColor: '#ffffff',
    borderRadius: 24,
    paddingVertical: 18,
    paddingHorizontal: 18,
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 4,
  },
  perfHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  perfHeaderInfo: {
    flex: 1,
  },
  perfTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8a86a8',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  perfValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  perfValue: {
    fontSize: 30,
    fontWeight: '800',
    color: '#1a1a2e',
  },
  perfControlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  perfMenuButton: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#f1f1f5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  perfMenuButtonActive: {
    backgroundColor: '#efeaff',
    borderWidth: 1,
    borderColor: '#c9bfff',
  },
  perfMenuBackdrop: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 20,
  },
  perfMenuDropdown: {
    position: 'absolute',
    top: 54,
    right: 18,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    paddingVertical: 6,
    minWidth: 160,
    borderWidth: 1,
    borderColor: 'rgba(26, 26, 46, 0.08)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 8,
    zIndex: 30,
  },
  perfMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  perfMenuItemText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  perfMenuItemTextActive: {
    color: '#3c2ba7',
    fontWeight: '800',
  },
  perfDeltaChip: {
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  perfDeltaChipUp: {
    backgroundColor: '#d9f2e5',
  },
  perfDeltaChipDown: {
    backgroundColor: 'rgba(214, 69, 80, 0.12)',
  },
  perfDeltaText: {
    fontSize: 12,
    fontWeight: '800',
  },
  perfDeltaTextUp: {
    color: '#1f9d6d',
  },
  perfDeltaTextDown: {
    color: '#d64550',
  },
  perfDateLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8a86a8',
    marginTop: 2,
    textTransform: 'capitalize',
  },
  perfMetricLabel: {
    marginTop: 1,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '700',
    color: '#3c2ba7',
  },
  perfMetricDescriptor: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 12,
    backgroundColor: '#f4f1ff',
    paddingHorizontal: 9,
    paddingVertical: 6,
    marginTop: 2,
    marginBottom: 4,
  },
  perfMetricDescriptorText: {
    flexShrink: 1,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '600',
    color: '#595176',
  },
  perfHelpPanel: {
    borderRadius: 14,
    backgroundColor: '#f7f6fb',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(60, 43, 167, 0.16)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 4,
    marginBottom: 6,
  },
  perfHelpTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1a1a2e',
    marginBottom: 4,
  },
  perfHelpText: {
    fontSize: 11,
    lineHeight: 16,
    color: '#6f7a86',
  },
  perfHelpModeText: {
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    color: '#3c2ba7',
    marginTop: 5,
  },
  perfChartArea: {
    alignSelf: 'stretch',
    marginTop: 4,
  },
  perfXLabelsRow: {
    position: 'absolute',
    left: 34,
    right: 0,
    bottom: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  perfXLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#9a96b8',
    textTransform: 'capitalize',
  },
  perfEmptyState: {
    height: 170,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  perfEmptyText: {
    fontSize: 13,
    color: '#8a86a8',
    textAlign: 'center',
    lineHeight: 19,
  },
  perfPeriodRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    gap: 8,
  },
  perfPeriodButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#f1f1f5',
  },
  perfPeriodButtonActive: {
    backgroundColor: '#efeaff',
    borderWidth: 1.5,
    borderColor: '#3c2ba7',
  },
  perfPeriodText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#6f7a86',
  },
  perfPeriodTextActive: {
    color: '#3c2ba7',
  },
  perfScrubDateChip: {
    position: 'absolute',
    bottom: 0,
    width: 76,
    alignItems: 'center',
    backgroundColor: '#1a1a2e',
    borderRadius: 8,
    paddingVertical: 3,
  },
  perfScrubDateText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#ffffff',
    textTransform: 'capitalize',
  },
  // --- STYLES FOR PROFILE & CUSTOMIZE CALENDAR ---
  profileScrollContent: {
    alignItems: 'stretch',
    paddingTop: 16,
    paddingBottom: 36,
  },
  profileBody: {
    alignSelf: 'center',
  },
  profileMoodSection: {
    alignSelf: 'stretch',
    marginBottom: 24,
  },
  profileMoodRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  profileMoodCell: {
    alignItems: 'center',
    gap: 6,
  },
  profileMoodDayLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#8a86a8',
  },
  profileMoodEmojiCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#f6f6fb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileMoodEmojiCircleToday: {
    borderWidth: 1.5,
    borderColor: '#3c2ba7',
  },
  profileMoodEmoji: {
    fontSize: 18,
  },
  profileMoodImage: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  profileStatsSection: {
    alignSelf: 'stretch',
    marginBottom: 28,
  },
  profileStatsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a2e',
    marginBottom: 12,
  },
  profileStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  profileStatsRangeHint: {
    marginTop: 2,
    color: '#77738f',
    fontSize: 11,
    lineHeight: 16,
  },
  profileStatCard: {
    width: '48%',
    borderRadius: 20,
    backgroundColor: '#ffffff',
    padding: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  profileStatHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  profileStatLabel: {
    fontSize: 11,
    color: '#6f7a86',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    flexShrink: 1,
  },
  profileStatValueRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
  },
  profileStatValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1a1a2e',
  },
  profileStatUnit: {
    fontSize: 12,
    color: '#6f7a86',
    fontWeight: '600',
  },
  profileHeaderRow: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  profileHeaderTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1a1a2e',
  },
  profileSettingsButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  profileChipsScroll: {
    alignSelf: 'stretch',
    marginBottom: 16,
  },
  profileChipsContent: {
    paddingHorizontal: 24,
    gap: 8,
  },
  profileFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e4e8f2',
    backgroundColor: '#ffffff',
    paddingVertical: 8,
    paddingHorizontal: 14,
    maxWidth: 180,
  },
  profileFilterChipImage: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  profileFilterChipSelected: {
    backgroundColor: '#3c2ba7',
    borderColor: '#3c2ba7',
  },
  profileFilterChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  profileFilterChipTextSelected: {
    color: '#ffffff',
  },
  profileFilterSheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  profileFilterSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(26, 26, 46, 0.45)',
  },
  profileFilterSheetCard: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
    maxHeight: '70%',
  },
  profileFilterSheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#d8dbe8',
    marginBottom: 14,
  },
  profileFilterSheetTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a2e',
    marginBottom: 8,
  },
  profileFilterSheetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
  },
  profileFilterSheetOverallIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: '#edefff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileFilterSheetIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    resizeMode: 'cover',
  },
  profileFilterSheetEmoji: {
    fontSize: 22,
    width: 30,
    textAlign: 'center',
  },
  profileFilterSheetRowText: {
    flex: 1,
    fontSize: 15,
    color: '#1a1a2e',
  },
  profileFilterSheetRowTextSelected: {
    fontWeight: '700',
    color: '#3c2ba7',
  },
  profileFilterSheetPinButton: {
    padding: 4,
  },
  profileActionsRow: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    gap: 10,
  },
  profileSummaryActionCard: {
    alignSelf: 'stretch',
    minHeight: 72,
    marginBottom: 12,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2dff0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  profileSummaryActionIcon: {
    width: 42,
    height: 42,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#efedff',
  },
  profileSummaryActionText: {
    flex: 1,
  },
  profileSummaryActionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#292c40',
  },
  profileSummaryActionHint: {
    marginTop: 3,
    fontSize: 11,
    lineHeight: 15,
    color: '#74788b',
  },
  profileActionCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingVertical: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  profileActionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  settingsContent: {
    gap: 10,
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#f6f6fb',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  settingsRowDisabled: {
    opacity: 0.6,
  },
  settingsRowLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  settingsRowTextGroup: {
    flex: 1,
    gap: 3,
  },
  settingsRowTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  settingsRowHint: {
    fontSize: 12,
    lineHeight: 16,
    color: '#6f6b87',
  },
  settingsLanguageGroup: {
    flexDirection: 'row',
    gap: 6,
  },
  settingsLanguageButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d4dcf0',
    backgroundColor: '#ffffff',
    paddingVertical: 7,
    paddingHorizontal: 14,
  },
  settingsLanguageButtonActive: {
    backgroundColor: '#3c2ba7',
    borderColor: '#3c2ba7',
  },
  settingsLanguageText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#3c2ba7',
  },
  settingsLanguageTextActive: {
    color: '#ffffff',
  },
  profileTasksContainer: {
    flex: 1,
    backgroundColor: '#f6f6fb',
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 28,
  },
  profileTasksHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  profileTasksCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4e8f2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityHeaderText: {
    flex: 1,
    paddingRight: 16,
  },
  profileTasksTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1a1a2e',
  },
  profileTasksSubtitle: {
    fontSize: 13,
    color: '#6f7a86',
    marginTop: 4,
  },
  profileTasksList: {
    paddingBottom: 96,
  },
  profileTasksEmpty: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  profileTasksEmptyText: {
    fontSize: 14,
    color: '#6f7a86',
    textAlign: 'center',
    marginTop: 12,
  },
  profileTasksTabsPill: {
    flexDirection: 'row',
    backgroundColor: '#e9eaf4',
    borderRadius: 16,
    padding: 4,
    marginBottom: 16,
  },
  profileTasksTab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 11,
  },
  profileTasksTabActive: {
    backgroundColor: '#ffffff',
    shadowColor: '#1a1a2e',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  profileTasksTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6f7a86',
  },
  profileTasksTabTextActive: {
    color: '#3c2ba7',
  },
  profileTasksSectionHeader: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6f7a86',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 12,
    marginBottom: 8,
  },
  activityDayHeader: {
    fontSize: 13,
    fontWeight: '700',
    color: '#3c2ba7',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: 18,
    marginBottom: 6,
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e4e8f2',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
  },
  activityRowIcon: {
    marginRight: 10,
  },
  activityRowLabel: {
    fontSize: 14,
    color: '#1F2742',
  },
  activityRowContent: {
    flex: 1,
  },
  activityRowMeta: {
    marginTop: 3,
    fontSize: 12,
    color: '#7f8998',
  },
  activityReflectionMeta: {
    marginLeft: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  activityMoodEmoji: {
    fontSize: 16,
  },
  activityRowTime: {
    marginLeft: 8,
    fontSize: 12,
    color: '#9aa5b5',
  },
  activitySearchArea: {
    gap: 9,
    marginBottom: 12,
  },
  activityResultsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  activityResultsText: {
    fontSize: 12,
    color: '#7f8998',
  },
  activityClearFilters: {
    fontSize: 12,
    fontWeight: '700',
    color: '#3c2ba7',
  },
  activityShowMore: {
    alignSelf: 'center',
    borderRadius: 18,
    backgroundColor: '#edefff',
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginTop: 10,
  },
  activityShowMoreText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#3c2ba7',
  },
  profileTasksFilters: {
    gap: 12,
    marginBottom: 16,
  },
  profileTasksSearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4e8f2',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  profileTasksSearchInput: {
    flex: 1,
    fontSize: 14,
    color: '#1a1a2e',
  },
  profileTasksFilterRow: {
    gap: 8,
  },
  profileTasksFilterPill: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4e8f2',
  },
  profileTasksFilterPillActive: {
    backgroundColor: '#3c2ba7',
    borderColor: '#3c2ba7',
  },
  profileTasksFilterText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4a5364',
  },
  profileTasksFilterTextActive: {
    color: '#ffffff',
  },
  profileTasksBulkBar: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 24,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  profileTasksBulkText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1a1a2e',
  },
  profileTasksBulkDelete: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: '#ff6b6b',
  },
  profileTasksBulkDeleteText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
    textTransform: 'uppercase',
  },
  profileTasksBulkButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  profileTasksBulkAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: '#edefff',
  },
  profileTasksBulkActionText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#3c2ba7',
    textTransform: 'uppercase',
  },
  profileTaskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eceef6',
    borderRadius: 18,
    paddingVertical: 13,
    paddingHorizontal: 14,
    marginBottom: 10,
    shadowColor: '#1a1a2e',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  profileTaskRowSelected: {
    borderColor: '#3c2ba7',
    backgroundColor: '#f7f6ff',
  },
  profileTaskTitleArchived: {
    color: '#6f7a86',
  },
  profileTaskSelectCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#c5cadb',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  profileTaskSelectCircleActive: {
    backgroundColor: '#3c2ba7',
    borderColor: '#3c2ba7',
  },
  profileTaskStreakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#fff4e6',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginLeft: 10,
  },
  profileTaskStreakText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#e8590c',
  },
  profileTaskIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  profileTaskEmoji: {
    fontSize: 26,
  },
  profileTaskEmojiImage: {
    width: 40,
    height: 40,
    borderRadius: 14,
    resizeMode: 'cover',
  },
  profileTaskDetails: {
    flex: 1,
    marginLeft: 12,
  },
  profileTaskTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileTaskTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1a1a2e',
    flexShrink: 1,
  },
  profileTaskLockIcon: {
    marginLeft: 6,
  },
  profileTaskMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 6,
  },
  profileTaskMetaText: {
    fontSize: 12,
    color: '#6f7a86',
    fontWeight: '500',
    flexShrink: 1,
  },
  profileTaskTag: {
    backgroundColor: '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d7dbeb',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  profileTaskTagText: {
    fontSize: 11,
    color: '#3c2ba7',
    fontWeight: '600',
  },
  profileDetailOverlay: {
    flex: 1,
    backgroundColor: 'rgba(10, 12, 30, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  profileDetailBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  profileDetailCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 8,
  },
  profileDetailHeaderButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  profileDetailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  profileDetailHeaderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  profileDetailIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  profileDetailEmoji: {
    fontSize: 30,
  },
  profileDetailEmojiImage: {
    width: 52,
    height: 52,
    borderRadius: 16,
    resizeMode: 'cover',
  },
  profileDetailTitleBlock: {
    marginLeft: 14,
    flex: 1,
  },
  profileDetailTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a2e',
  },
  profileDetailTime: {
    marginTop: 4,
    fontSize: 13,
    color: '#6f7a86',
  },
  profileDetailArchivedBadge: {
    alignSelf: 'flex-start',
    marginTop: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: '#eef0f6',
  },
  profileDetailArchivedBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6f7a86',
  },
  profileDetailInfoCard: {
    backgroundColor: '#f7f8fc',
    borderRadius: 16,
    paddingHorizontal: 14,
  },
  profileDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e6e8f2',
  },
  profileDetailRowLast: {
    borderBottomWidth: 0,
  },
  profileDetailLabel: {
    fontSize: 13,
    color: '#6f7a86',
    fontWeight: '600',
    flexShrink: 0,
  },
  profileDetailValue: {
    fontSize: 13,
    color: '#1a1a2e',
    fontWeight: '600',
    flex: 1,
    marginLeft: 12,
    textAlign: 'right',
  },
  profileDetailActions: {
    marginTop: 20,
    flexDirection: 'row',
    gap: 8,
  },
  profileDetailGoalButton: {
    flex: 1,
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d9d5ed',
    backgroundColor: '#f4f2ff',
    gap: 7,
  },
  profileDetailGoalButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#3c2ba7',
    textAlign: 'center',
  },
  profileDetailLockButton: {
    flex: 1,
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#3c2ba7',
    gap: 8,
  },
  profileDetailLockButtonActive: {
    backgroundColor: '#3c2ba7',
  },
  profileDetailLockButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#3c2ba7',
  },
  profileDetailLockButtonTextActive: {
    color: '#ffffff',
  },
  profileDetailActionsSecondary: {
    marginTop: 8,
    flexDirection: 'row',
    gap: 8,
  },
  profileDetailArchiveButton: {
    flex: 1,
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d9d5ed',
    gap: 7,
  },
  profileDetailArchiveButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#3c2ba7',
  },
  profileDetailDeleteButton: {
    flex: 1,
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ffd4d4',
    gap: 7,
  },
  profileDetailDeleteButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#e03131',
  },
  
  // Customize Modal Styles
  customizeModalContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  customizeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  customizeTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1a1a2e',
  },
  customizeScrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  customizeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  customizeCard: {
    flex: 1,
    height: 80,
    borderRadius: 16,
    overflow: 'hidden',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  customizeCardText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    zIndex: 1,
  },
  customizeAddButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: '#3c2ba7',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
    backgroundColor: '#fff',
  },
});
